const tintColorLight = "#0a7ea4";
const tintColorDark = "#fff";

export const Colors = {
  light: {
    btnText: "white",
    primary: "#89163a",
    secondary: "#dcddde",
    borderColor: "black",
    primaryBackground: "white",
    secondaryBackground: "#ffedef",
    primaryText: "black",
    secondaryText: "#8c0434",
    tertiaryText: "#bd979e",

    
    text: "#1a1a1a",
    lighterText: "#6b7280",
    lightestText: "#9ca3af",
    primaryRed: "#c92422",
    primaryGreen: "#4da34c",
    primaryBlue: "#435ff2",
    secondaryRed: "#f7e3e2",
    secondaryGreen: "#e4fbe8",
    tint: tintColorLight,
    icon: "#687076",
    tabIconDefault: "#687076",
    tabIconSelected: tintColorLight,
    searchText: "#999",
    searchBar: "#f3f3f5",
  },
  dark: {
    btnText: "white",
    primary: "#da1d52",
    secondary: "#efe1d3",
    borderColor: "white",
    primaryBackground: "black",
    secondaryBackground: "#1a1215",
    primaryText: "white",
    secondaryText: "#ba949b",
    tertiaryText: "#c9bdbf",

    text: "#e6e6e6",
    lighterText: "#808793",
    lightestText: "#505762",
    primaryRed: "#d5413f",
    primaryGreen: "#61af60",
    primaryBlue: "#667efa",
    secondaryRed: "#1b0a09",
    secondaryGreen: "#051a08",
    tint: tintColorDark,
    icon: "#9BA1A6",
    tabIconDefault: "#9BA1A6",
    tabIconSelected: tintColorDark,
    searchText: "#666",
    searchBar: "#09090b",
  },
};